INSERT INTO HUB_PLANT (PLANT_NK, PLANT_PK, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11) VALUES
('PLANT003-LA', 1.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('PLANT002-CHI', 2.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('PLANT001-NYC', 3.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('PLANT004-HOU', 4.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('PLANT005-DAL', 5.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0);